name: Static Analysis

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

  # 'workflow_dispatch' allows manual execution of this workflow under the repository's 'Actions' tab
  workflow_dispatch:

jobs:

  cppcheck-analysis:
    name: cppcheck-analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install CppCheck
        run: sudo apt install -y cppcheck

      - name: Execute CppCheck on header files
        run: cppcheck --std=c99 --error-exitcode=-1 --addon=misra.py $PWD/include/predict/*

      - name: Execute CppCheck on source files
        run: cppcheck --std=c99 --error-exitcode=-1 --addon=misra.py -I$PWD/include/ $PWD/src/*
